AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false
